### ISSUE TITLE
can't build example on Ubuntu 15.04

### ISSUE THREAD

**Issue by avilleret** [2bbb/ofxWebUI#1]
here is the log : https://gist.github.com/avilleret/31e272d48d13a8b7c9df
look at line 27
it is too long for my compiler

**Comment by 2bbb** [comment]
can you build example of ofxNodejs on ubuntu?

**Comment by avilleret** [comment]
no but other reasons

**Comment by avilleret** [comment]
see https://github.com/satoruhiga/ofxNodejs/issues/5

**Comment by 2bbb** [comment]
sorry, i can't understand language in your error log.
but maybe, this article will help you.
http://forum.openframeworks.cc/t/of-boost-on-raspberry-pi-2/20032
https://github.com/openframeworks/openFrameworks/issues/3009

and, i think, ofxNodejs use static library of node that is provided for only osx.
so, you can't run app if you can build this project.

**Comment by 2bbb** [comment]
ah, you see this?
https://github.com/satoruhiga/ofxNodejs/blob/master/libs/build_osx.sh
this build of node is customized.

and i and satoruhiga don't use ubuntu hard.
let's write build_ubuntu.sh and make ubuntu binary, and post PR!! :+1:

**Comment by avilleret** [comment]
> sorry, i can't understand language in your error log.

It's a shame, there are just build log...

> but maybe, this article will help you.
> http://forum.openframeworks.cc/t/of-boost-on-raspberry-pi-2/20032
> openframeworks/openFrameworks#3009

I don't understand how that could help me...

>  ofxNodejs use static library of node that is provided for only osx.

yes, this is mandatory to release iOS app.
and I don't see any pb to link to shared lib instead of static on Linux.

**Comment by 2bbb** [comment]
> It's a shame, there are just build log…

i know there are just build log.
but i can't read your native language. is it french? or other?
you can't change language to english?
if you can't do it, it's a shame too.

**Comment by avilleret** [comment]
? the build logs I post are all in English !
at least error are displayed in English after a quick check.

anyway I found the culprit.
ofMain.h defines some alias like `True` `False` `None` and `node.h` defines them too without checking if there are already defined...
The first step is to swap the inclusion of `v8.h` and `ofMain.h`

**Comment by avilleret** [comment]
Unfortunately swapping header is not enough.
There are still conflict between of and nodejs declaration.

Also I update to 0.12 instead of 0.10 and it doesn't change anything.

**Comment by 2bbb** [comment]
ah yeah, sorry. i see.
(but NOT ALL. i thought most important message and saw at first is `Liste d'arguments trop longue`. but i don't know this message in english. 😝)

this build under v0.10.35, and now (v0.12.x too) many parts of v8 has changed.
i think, if you want to use v4.x on Ubuntu, you must do it yourself.

and we will know your problem is caused by ofxWebUI or not, after you can build example of ofxNodejs.

i think, i can't help you now. because i don't think this problem is caused by my code.
if you will get success to build ofxNodejs, and get problem again, please reopen this issue.

**Comment by avilleret** [comment]
ho sorry, I think this is the only French sentence.
and it means : "Arguments list too long"
pretty obvious, isn't ?

**Comment by 2bbb** [comment]
sorry, sorry.
i presented you: http://forum.openframeworks.cc/t/of-boost-on-raspberry-pi-2/20032
and this article about `execv: Argument list too long`.

okay, i agree to i'm not genius as you.
so, let's google it or develop everything yourself. you can do it.

**Comment by avilleret** [comment]
sorry I never wanted to hurt you.
I just want to help you by reporting issue.

**Comment by 2bbb** [comment]
sorry, i had lost my temper…
and don't worry, you don't hurt me. maybe 

but sadly, maybe it is fact that i can't help you.
